# This is a basic workflow to help you get started with Actions
# python :https://docs.github.com/ja/actions/automating-builds-and-tests/building-and-testing-python

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup:
    name: Setup
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests
          git clone https://gitlab.com/enish-tool/fetch.git
  run-1:
      needs:
      - setup
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v4
      - name: Run 1
        run: python fetch/main.py
  run-2:
      needs:
      - setup
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v4
      - name: Run 2
        run: python fetch/main.py
  run-3:
      name: Run3
      needs:
      - setup
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v4
      - name: Run
        run: python fetch/main.py
  run-4:
      name: Run4
      needs:
      - setup
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v4
      - name: Run
        run: python fetch/main.py
  build:
      name: stage push
      needs: 
       - run-1
       - run-2
       - run-3
       - run-4
      runs-on: ubuntu-latest
      steps:
        - name: push
          run: |
           git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
           git config --global user.name "${GITHUB_ACTOR}"
           git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
           if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "[ci skip]"; \
            git push origin HEAD:${GITHUB_REF}; \
           fi
